Always available:
游릴 Fireballs
游릴 Ladders
游릴 Silverfish
游릴 TNT
游릴 Milk
游릴 Bridge eggs
游릴 Blue side
游릴 Diamond armor
Anything else not listed under the restricted or banned items is allowed

Available after one bed is broken:
游릳 Water
游릳 Diamond sword
游릳 All pots
游릳 Pearls
游릳 KB Sticks
游릳 Both sides

Banned items:
游린 Golems
游린 All bows
游린 Obsidian